## this setup will build the markdown files automatically, when code is pushed into github repository.

name: Vitepress Starter CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  #1st CI job
  build_markdown:
    name: Build markdown
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install
      
      - name: Create Working Build
        run: npm run docs:build
      
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages # The branch name where you want to push the assets
          FOLDER: docs/.vitepress/dist # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
      
#       - name: Commit UI
#         run: |
#           cd docs/.vitepress/dist
#           git config --global user.name "abc"
#           git config --global user.email 'abc@users.noreply.github.com'
#           git commit -am 'deploy'
#           git push -f git@github.com:sayyidkhan/vitepress-starter-v2.git master:gh-pages
          
